projeto/quatro/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'welcome/index'

  resources :casas

end

projeto/quatro/app/models/casa.rb
class Casa < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :age
end

projeto/quatro/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

projeto/quatro/app/controllers/casas_controller.rb
class CasasController < ApplicationController
  before_action :set_casa, only: [:show, :edit, :update, :destroy]

  # GET /casas
  # GET /casas.json
  def index
    @casas = Casa.all
  end

  # GET /casas/1
  # GET /casas/1.json
  def show
  end

  # GET /casas/new
  def new
    @casa = Casa.new
  end

  # GET /casas/1/edit
  def edit
  end

  # POST /casas
  # POST /casas.json
  def create
    @casa = Casa.new(casa_params)

    respond_to do |format|
      if @casa.save
        format.html { redirect_to @casa, notice: 'Criado com sucesso.' }
        format.json { render :show, status: :created, location: @casa }
      else
        format.html { render :new }
        format.json { render json: @casa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casas/1
  # PATCH/PUT /casas/1.json
  def update
    respond_to do |format|
      if @casa.update(casa_params)
        format.html { redirect_to @casa, notice: 'Atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @casa }
      else
        format.html { render :edit }
        format.json { render json: @casa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casas/1
  # DELETE /casas/1.json
  def destroy
    @casa.destroy
    respond_to do |format|
      format.html { redirect_to casas_url, notice: 'Deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_casa
      @casa = Casa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def casa_params
      params.require(:casa).permit(:name, :age.to_s)
    end
end

projeto/quatro/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

projeto/quatro/app/helpers/application_helper.rb
module ApplicationHelper
end

projeto/quatro/app/helpers/casas_helper.rb
module CasasHelper
end

projeto/quatro/app/helpers/welcome_helper.rb
module WelcomeHelper
end

projeto/quatro/app/views/casas/_form.html.erb
<%= form_for @casa, :html => { :class => "form-horizontal casa" } do |f| %>

  <% if @casa.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@casa.errors.count, "erro") %> Todos os campos deverão ser preenchidos:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @casa.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :age, :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
      <%= f.text_field :age, :class => 'form-control' %>
    </div>
    <%=f.error_span(:age) %>
  </div>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                casas_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

projeto/quatro/app/views/casas/edit.html.erb
<%- model_class = Casa -%>
<div class="page-header">
  <h1>Editar Cadastro</h1>
</div>
<%= render :partial => 'form' %>

projeto/quatro/app/views/casas/index.html.erb
<%- model_class = Casa -%>
<div class="page-header">
  <h1>Cadastro</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @casas.each do |casa| %>
      <tr>
        <td><%= link_to casa.id, casa_path(casa) %></td>
        <td><%= casa.name %></td>
        <td><%= casa.age %></td>
        <td><%= casa.created_at %></td>
        <td><%= casa.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_casa_path(casa), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      casa_path(casa),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_casa_path,
            :class => 'btn btn-primary' %>

projeto/quatro/app/views/casas/new.html.erb
<%- model_class = Casa -%>
<div class="page-header">
  <h1>Novo Cadastro</h1>
</div>
<%= render :partial => 'form' %>

projeto/quatro/app/views/casas/show.html.erb
<%- model_class = Casa -%>
<div class="page-header">
  <h1>Cadastro</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @casa.name %></dd>
  <dt><strong>Idade:</strong></dt>
  <dd><%= @casa.age %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              casas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_casa_path(@casa), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              casa_path(@casa),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>


<!--<%= model_class.human_attribute_name(:age) %> -->

projeto/quatro/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Blog</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3></h3>
            <ul class="nav nav-list">
              <li><%= link_to "Início", root_path  %></li>
              <li><%= link_to "Adicionar Pessoas", casas_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

projeto/quatro/app/views/welcome/index.html.erb
<h1>Cadastro de Pessoas</h1>
<p></p>